services:
  - type: web
    name: nezu-homepilot-api
    rootDirectory: backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: nezu-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: HOMEASSISTANT_URL
        sync: false
      - key: HOMEASSISTANT_TOKEN
        sync: false
